// Project data for the portfolio page.
// Edit descriptions and other fields here — the page reads this file at load time.

const PROJECTS = [
  {
    "num": 1,
    "from": "2012-01",
    "to": "2012-05",
    "months": 4,
    "industry": "Automotive",
    "level": "Professional",
    "type": "IT Project",
    "naming": "ok to name",
    "organization": "Robert Bosch GmbH",
    "customer": "Robert Bosch GmbH",
    "category": "",
    "country": "Germany",
    "role": "Project member",
    "resp": "Implementation, Communication",
    "tech": "Powerpoint, Visio",
    "ref": "yes",
    "desc_en": "Supported an international IT project consolidating sales software across business units. Areas of responsibility: process management rollout, usability, testing, development support, knowledge management.",
    "desc_de": "Unterstützung eines internationalen IT-Projekts zur Konsolidierung von Sales-Software über Geschäftsbereiche hinweg. Verantwortungsbereiche: Prozessmanagement-Rollout, Usability, Testing, Entwicklungsunterstützung, Wissensmanagement."
  },
  {
    "num": 2,
    "from": "2013-05",
    "to": "2013-08",
    "months": 4,
    "industry": "Insurance",
    "level": "Professional",
    "type": "IT Project",
    "naming": "keep anonymous",
    "organization": "Accenture",
    "customer": "",
    "category": "Top 3 Insurance",
    "country": "Germany",
    "role": "Project member",
    "resp": "Implementation, Communication",
    "tech": "VBA, Excel, Powerpoint",
    "ref": "yes",
    "desc_en": "Supported an IT project implementing new core software at a German insurance company. Owned test management; optimized the reporting process by extending existing VBA expertise.",
    "desc_de": "Teammitglied im IT-Projektmanagement für die Einführung einer neuen Kern-Software bei einem deutschen Versicherer. Zuständig für Testmanagement, Optimierung des Reporting-Prozesses durch Nutzung und Weiterentwicklung bestehender VBA-Kenntnisse."
  },
  {
    "num": 3,
    "from": "2015-02",
    "to": "2015-04",
    "months": 3,
    "industry": "Insurance",
    "level": "Professional",
    "type": "IT Project",
    "naming": "keep anonymous",
    "organization": "McKinsey",
    "customer": "",
    "category": "Top 3 Insurance",
    "country": "Germany",
    "role": "Project member",
    "resp": "Implementation, Communication",
    "tech": "Excel, Powerpoint",
    "ref": "yes",
    "desc_en": "Developed an approach for volume-based pricing of IT-services between corporate entities. Supported buildup of the line organization for Controlling, Portfolio Mgmt, and Project Mgmt of a new corporate entity.",
    "desc_de": "Entwicklung eines Ansatzes für volumenbasierte Verrechnung von IT-Services zwischen Konzerneinheiten. Unterstützung des Aufbaus der Linienorganisation für Controlling, Portfolio-Management und Projektmanagement einer neuen Konzerneinheit."
  },
  {
    "num": 4,
    "from": "2015-09",
    "to": "2015-09",
    "months": 0.5,
    "industry": "Retail",
    "level": "Student",
    "type": "Data Science Project",
    "naming": "ok to name",
    "organization": "Northwestern University",
    "customer": "Enova International",
    "category": "",
    "country": "United States",
    "role": "Project lead",
    "resp": "Implementation, Communication, Stakeholder Mgmt",
    "tech": "R, Powerpoint",
    "ref": "",
    "desc_en": "Predicted retail value of diamonds (using linear regression) based on properties such as color, weight, purity.",
    "desc_de": "Vorhersage des Einzelhandelswerts von Diamanten (mittels linearer Regression) basierend auf Eigenschaften wie Farbe, Gewicht und Reinheit."
  },
  {
    "num": 5,
    "from": "2015-09",
    "to": "2015-12",
    "months": 3,
    "industry": "Retail",
    "level": "Student",
    "type": "Data Science Project",
    "naming": "ok to name",
    "organization": "Northwestern University",
    "customer": "Trunk Club",
    "category": "",
    "country": "United States",
    "role": "Project member",
    "resp": "Implementation, Communication, Stakeholder Mgmt",
    "tech": "R, SQL, Powerpoint",
    "ref": "",
    "desc_en": "Forecasted demand for an online fashion retailer using random forests; derived business decision support for marketing and logistics.",
    "desc_de": "Nachfrageprognose für einen Online-Fashion-Retailer mittels Random Forests; Ableitung von Entscheidungsunterstützung für Marketing und Logistik."
  },
  {
    "num": 6,
    "from": "2016-01",
    "to": "2016-06",
    "months": 6,
    "industry": "Public Sector",
    "level": "Student",
    "type": "Data Science Project",
    "naming": "ok to name",
    "organization": "Northwestern University",
    "customer": "Chicago Park District",
    "category": "",
    "country": "United States",
    "role": "Project lead",
    "resp": "Implementation, Communication, Stakeholder Mgmt",
    "tech": "R, D3, Powerpoint",
    "ref": "",
    "desc_en": "\"The Power of Parks\": Built statistical models (random forests, boosted trees, neural networks) explaining the effect of the US' largest public park system on nearby property values. Predicted demand for public activity programs. Ran sentiment analysis on structured and unstructured data from 10,000+ survey responses.",
    "desc_de": "„The Power of Parks\": Statistische Modelle (Random Forests, Boosted Trees, neuronale Netze) zur Erklärung des Effekts des größten US-Park-Systems auf umliegende Immobilienwerte. Vorhersage der Nachfrage nach öffentlichen Aktivitätsprogrammen. Sentiment-Analyse auf strukturierten und unstrukturierten Daten aus 10.000+ Umfrageantworten."
  },
  {
    "num": 7,
    "from": "2016-05",
    "to": "2016-06",
    "months": 1,
    "industry": "Telecommunications",
    "level": "Student",
    "type": "Data Science Project",
    "naming": "ok to name",
    "organization": "Northwestern University",
    "customer": "Suddenlink",
    "category": "",
    "country": "United States",
    "role": "Project lead",
    "resp": "Implementation, Communication, Stakeholder Mgmt",
    "tech": "R, Powerpoint",
    "ref": "",
    "desc_en": "\"Cord cutters\": Predicted churn likelihood of cable TV subscribers (using random forests, boosted trees and ensemble methods) based on set-top box activity data.",
    "desc_de": "„Cord cutters\": Vorhersage der Churn-Wahrscheinlichkeit von Kabel-TV-Abonnent:innen (mittels Random Forests, Boosted Trees und Ensemble-Methoden) anhand von Set-Top-Box-Aktivitätsdaten."
  },
  {
    "num": 8,
    "from": "2016-06",
    "to": "2016-09",
    "months": 3,
    "industry": "Public Sector",
    "level": "Student",
    "type": "Data Science Project",
    "naming": "ok to name",
    "organization": "United Nations",
    "customer": "United Nations",
    "category": "",
    "country": "Switzerland",
    "role": "Project lead",
    "resp": "Implementation, Communication, Stakeholder Mgmt",
    "tech": "R, Powerpoint",
    "ref": "yes",
    "desc_en": "Built a model (using an ensemble of random forests, boosted trees and neural networks) explaining migration flows in African countries, linking census data and a dataset on violent outbreaks.",
    "desc_de": "Modell (Ensemble aus Random Forests, Boosted Trees und neuronalen Netzen) zur Erklärung von Migrationsströmen in afrikanischen Ländern, basierend auf der Verknüpfung von Zensus-Daten und einem Datensatz zu gewaltsamen Ausbrüchen."
  },
  {
    "num": 9,
    "from": "2016-10",
    "to": "2016-12",
    "months": 3,
    "industry": "Information Technology",
    "level": "Student",
    "type": "Data Science Project",
    "naming": "ok to name",
    "organization": "Northwestern University",
    "customer": "HERE Technologies",
    "category": "",
    "country": "United States",
    "role": "Project lead",
    "resp": "Implementation, Communication, Stakeholder Mgmt",
    "tech": "R, Powerpoint",
    "ref": "",
    "desc_en": "Predicted true location of highway construction zones based on vehicle navigation data in collaboration with the customer, using descriptive and predictive analytics (boosted trees, random forests, deep neural networks, ensemble methods). Led a team of five students through all project stages from obtaining data to final presentation and write-up of a white paper.",
    "desc_de": "Vorhersage der tatsächlichen Position von Autobahn-Baustellen anhand von Fahrzeug-Navigationsdaten in Zusammenarbeit mit dem Kunden, mittels deskriptiver und prädiktiver Analytik (Boosted Trees, Random Forests, Deep Neural Networks, Ensemble-Methoden). Führung eines fünfköpfigen Studententeams durch alle Projektphasen — von der Datenbeschaffung bis zur Abschlusspräsentation und zum White Paper."
  },
  {
    "num": 10,
    "from": "2017-02",
    "to": "2017-02",
    "months": 1,
    "industry": "Chemicals",
    "level": "Professional",
    "type": "Data Science Project",
    "naming": "keep anonymous",
    "organization": "McKinsey",
    "customer": "",
    "category": "Top 3 Chemical company",
    "country": "Germany",
    "role": "Project member",
    "resp": "Implementation, Communication",
    "tech": "VBA, Excel",
    "ref": "yes",
    "desc_en": "Implemented and extended an economic model for price movement of chemical commodities to support C-suite with long-term investment decisions, using Excel and VBA.",
    "desc_de": "Implementierung und Erweiterung eines ökonomischen Modells zur Vorhersage von Preisbewegungen chemischer Commodities zur Unterstützung der C-Suite bei langfristigen Investitionsentscheidungen, mit Excel und VBA."
  },
  {
    "num": 11,
    "from": "2017-03",
    "to": "2017-05",
    "months": 3,
    "industry": "Mining",
    "level": "Professional",
    "type": "Data Science Project",
    "naming": "keep anonymous",
    "organization": "McKinsey",
    "customer": "",
    "category": "Top 3 Mining company",
    "country": "Belgium",
    "role": "Project member",
    "resp": "Implementation, Communication",
    "tech": "VBA, Gurobi Solver, Excel",
    "ref": "",
    "desc_en": "Built and implemented a production-planning optimization tool for reducing waste and maximizing output of a Western European mine with about 200 workers and 50 machines permanently on-site. Delivered dedicated data/analytics enablement sessions for non-technical customer stakeholders.",
    "desc_de": "Aufbau und Einführung eines Produktionsplanungs-Optimierungstools zur Reduzierung von Ausschuss und Maximierung des Outputs einer westeuropäischen Mine mit rund 200 Mitarbeitenden und 50 fest stationierten Maschinen. Durchführung dedizierter Data-/Analytics-Enablement-Sessions für nicht-technische Stakeholder beim Kunden."
  },
  {
    "num": 12,
    "from": "2017-05",
    "to": "2017-12",
    "months": 7,
    "industry": "Insurance",
    "level": "Professional",
    "type": "Data Science Project",
    "naming": "keep anonymous",
    "organization": "McKinsey",
    "customer": "",
    "category": "Top 10 Insurance",
    "country": "Germany",
    "role": "Project member",
    "resp": "Strategy, Implementation, Communication, Stakeholder Mgmt",
    "tech": "R, Excel, Powerpoint",
    "ref": "yes",
    "desc_en": "New-business buildout for a digital insurance subsidiary of a large German insurance group. Developed the analytics strategy and implemented novel, analytics-based pricing mechanisms for individual insurance products. Created innovative approach for market-based pricing, taking into account competitor price data from comparison websites.",
    "desc_de": "Neugeschäftsaufbau für ein digitales Versicherungsunternehmen einer großen deutschen Versicherungsgruppe. Entwicklung der Analytics-Strategie. Einführung neuartiger, analytics-basierter Pricing-Mechanismen für einzelne Versicherungsprodukte. Entwicklung eines innovativen Ansatzes für marktbasiertes Pricing unter Berücksichtigung von Wettbewerberpreisen aus Vergleichsportalen."
  },
  {
    "num": 13,
    "from": "2018-01",
    "to": "2018-04",
    "months": 4,
    "industry": "Telecommunications",
    "level": "Professional",
    "type": "Data Science Project",
    "naming": "keep anonymous",
    "organization": "McKinsey",
    "customer": "",
    "category": "Top 3 Telco",
    "country": "Switzerland",
    "role": "Project member",
    "resp": "Implementation, Communication",
    "tech": "R, Excel, Powerpoint",
    "ref": "yes",
    "desc_en": "Predicted churn likelihood of mobile phone customers (ensemble methods) based on demographics and activity data. Built and executed a tiered marketing response management tool for reducing actual churn, based on predicted reasons for customers with high churn probability. Delivered dedicated data/analytics enablement sessions for non-technical customer stakeholders.",
    "desc_de": "Vorhersage der Churn-Wahrscheinlichkeit von Mobilfunkkund:innen (Ensemble-Methoden) anhand von Demografie- und Aktivitätsdaten. Aufbau und Einführung eines gestaffelten Marketing-Response-Tools zur Reduzierung tatsächlichen Churns, basierend auf vorhergesagten Churn-Gründen bei Kund:innen mit hoher Abwanderungswahrscheinlichkeit. Durchführung dedizierter Data-/Analytics-Enablement-Sessions für nicht-technische Stakeholder beim Kunden."
  },
  {
    "num": 14,
    "from": "2018-05",
    "to": "2018-07",
    "months": 3,
    "industry": "Health Insurance (public)",
    "level": "Professional",
    "type": "Data Science Project",
    "naming": "keep anonymous",
    "organization": "McKinsey",
    "customer": "",
    "category": "Top 10 Health Insurance",
    "country": "Germany",
    "role": "Project member",
    "resp": "Implementation, Communication",
    "tech": "R, Excel, Powerpoint",
    "ref": "yes",
    "desc_en": "Developed models for predicting claims fraud from 800,000 yearly invoices (using boosted trees). Built a decision engine on top of the predictive model to prioritize claimants for follow-up interventions. Delivered dedicated data/analytics enablement sessions for non-technical customer stakeholders.",
    "desc_de": "Entwicklung von Modellen zur Vorhersage von Versicherungsbetrug aus 800.000 jährlichen Rechnungen (mittels Boosted Trees). Aufbau einer Decision-Engine auf Basis des Vorhersagemodells zur Priorisierung von Anspruchstellenden für Folge-Interventionen. Durchführung dedizierter Data-/Analytics-Enablement-Sessions für nicht-technische Stakeholder beim Kunden."
  },
  {
    "num": 15,
    "from": "2018-07",
    "to": "2018-07",
    "months": 1,
    "industry": "Consulting",
    "level": "Professional",
    "type": "Data Science Project",
    "naming": "ok to name",
    "organization": "McKinsey",
    "customer": "McKinsey",
    "category": "",
    "country": "Germany",
    "role": "Project lead",
    "resp": "Implementation, Communication, Stakeholder Mgmt",
    "tech": "R, Powerpoint, Pen & Paper",
    "ref": "yes",
    "desc_en": "Conceptualized, implemented and organized Europe-wide Data Science training sessions for consultants; instructed several sessions myself as a data scientist.",
    "desc_de": "Konzeption, Umsetzung und Organisation europaweiter Data-Science-Trainings für Berater:innen; mehrere Sessions selbst als Data Scientist gehalten."
  },
  {
    "num": 16,
    "from": "2018-08",
    "to": "2018-10",
    "months": 3,
    "industry": "Manufacturing",
    "level": "Professional",
    "type": "Data Science Project",
    "naming": "keep anonymous",
    "organization": "McKinsey",
    "customer": "",
    "category": "Top 3 Agricultural Machinery Maker",
    "country": "Germany",
    "role": "Project member",
    "resp": "Implementation, Communication",
    "tech": "R, Tableau, Alteryx, Excel, Powerpoint",
    "ref": "",
    "desc_en": "Built early parts defect prediction model based on Weibull distribution failure simulations - conceptualized, built and implemented various Tableau dashboards for services team to get early indication of faulty parts.",
    "desc_de": "Aufbau eines Bauteil-Defekt-Frühvorhersagemodells auf Basis von Weibull-Ausfallsimulationen — Konzeption, Aufbau und Einführung verschiedener Tableau-Dashboards für das Service-Team zur frühen Erkennung fehlerhafter Bauteile."
  },
  {
    "num": 17,
    "from": "2018-10",
    "to": "2018-11",
    "months": 1,
    "industry": "Consulting",
    "level": "Professional",
    "type": "Data Science Project",
    "naming": "ok to name",
    "organization": "McKinsey",
    "customer": "McKinsey",
    "category": "",
    "country": "Germany",
    "role": "Project lead",
    "resp": "Implementation, Communication, Stakeholder Mgmt",
    "tech": "R, Powerpoint, Pen & Paper",
    "ref": "yes",
    "desc_en": "Conceptualized, implemented and organized Europe-wide Data Science training sessions for consultants; instructed several sessions myself as a data scientist.",
    "desc_de": "Konzeption, Umsetzung und Organisation europaweiter Data-Science-Trainings für Berater:innen; mehrere Sessions selbst als Data Scientist gehalten."
  },
  {
    "num": 18,
    "from": "2018-11",
    "to": "2018-12",
    "months": 2,
    "industry": "Health Insurance (private)",
    "level": "Professional",
    "type": "Data Science Project",
    "naming": "keep anonymous",
    "organization": "McKinsey",
    "customer": "",
    "category": "Top 20 Health Insurance",
    "country": "Germany",
    "role": "Project member",
    "resp": "Implementation, Communication",
    "tech": "R, Alteryx, Excel, Powerpoint",
    "ref": "yes",
    "desc_en": "Spend analysis: Developed descriptive dashboards showing costs by ICD-10 sickness code category. Benchmarked against national averages and derived decision-support solutions for deep-diving into overspend.",
    "desc_de": "Spend-Analyse: Entwicklung deskriptiver Dashboards zur Darstellung von Kosten nach ICD-10-Krankheitskategorie. Benchmarking gegen nationale Durchschnittswerte und Ableitung von Decision-Support-Lösungen für Deep-Dives in Überausgaben."
  },
  {
    "num": 19,
    "from": "2019-01",
    "to": "2019-03",
    "months": 3,
    "industry": "Health Insurance (public)",
    "level": "Professional",
    "type": "Data Science Project",
    "naming": "keep anonymous",
    "organization": "McKinsey",
    "customer": "",
    "category": "Top 15 Health Insurance",
    "country": "Germany",
    "role": "Project member",
    "resp": "Implementation, Communication",
    "tech": "R, Alteryx, Excel, Powerpoint",
    "ref": "yes",
    "desc_en": "Claims analysis: Developed descriptive and predictive analyses (boosted trees) to assess and optimize the claims process for a given healthcare category , improving effectiveness and reducing fraud.",
    "desc_de": "Claims-Analyse: Entwicklung deskriptiver und prädiktiver Analysen (Boosted Trees) zur Bewertung und Optimierung des Schadenbearbeitungsprozesses für eine bestimmte Healthcare-Kategorie, mit dem Ziel höherer Effektivität und reduzierten Betrugs."
  },
  {
    "num": 20,
    "from": "2019-03",
    "to": "2019-12",
    "months": 8,
    "industry": "Health Insurance (public)",
    "level": "Professional",
    "type": "Data Science Project",
    "naming": "keep anonymous",
    "organization": "McKinsey",
    "customer": "",
    "category": "Top 3 Health Insurance",
    "country": "Germany",
    "role": "Project member",
    "resp": "Implementation, Communication, Stakeholder Mgmt",
    "tech": "R, Python, Tableau, Excel, Powerpoint",
    "ref": "yes",
    "desc_en": "Developed descriptive dashboards and predictive solutions for understanding unmet customer needs as part of a large Customer-Experience Transformation. Conceptualized a new set of feedback forms and built hierarchical predictive models that minimize question count while preserving insight quality and actionability, utilizing feature impact methods.",
    "desc_de": "Entwicklung deskriptiver Dashboards und prädiktiver Lösungen zum Verständnis unerfüllter Kundenbedürfnisse im Rahmen einer großen Customer-Experience-Transformation. Konzeption und Entwicklung eines neuen Sets von Feedback-Fragebögen sowie hierarchischer Vorhersagemodelle zum Verständnis von Zusammenhängen — mit dem Ziel, die Fragebogenlänge zu minimieren bei gleichbleibender Insight-Qualität und Handlungsableitung, unter Einsatz von Feature-Impact-Methoden."
  },
  {
    "num": 21,
    "from": "2019-10",
    "to": "2019-10",
    "months": 0.5,
    "industry": "Health Insurance (public)",
    "level": "Professional",
    "type": "Project Proposal",
    "naming": "keep anonymous",
    "organization": "McKinsey",
    "customer": "",
    "category": "Top 3 Health Insurance",
    "country": "Germany",
    "role": "Project member",
    "resp": "Communication",
    "tech": "Powerpoint",
    "ref": "yes",
    "desc_en": "Wrote project proposals for new Data Science engagements. Delivered dedicated data/analytics enablement sessions for non-technical customer stakeholders.",
    "desc_de": "Verfassen von Projektvorschlägen für neue Data-Science-Engagements. Durchführung dedizierter Data-/Analytics-Enablement-Sessions für nicht-technische Stakeholder beim Kunden."
  },
  {
    "num": 22,
    "from": "2019-12",
    "to": "2019-12",
    "months": 0.5,
    "industry": "Public Sector",
    "level": "Professional",
    "type": "Project Proposal",
    "naming": "keep anonymous",
    "organization": "McKinsey",
    "customer": "",
    "category": "German Federal Agency",
    "country": "Germany",
    "role": "Project member",
    "resp": "Communication",
    "tech": "Powerpoint",
    "ref": "yes",
    "desc_en": "Wrote project proposals for new Data Science engagements.",
    "desc_de": "Verfassen von Projektvorschlägen für neue Data-Science-Engagements."
  },
  {
    "num": 23,
    "from": "2020-01",
    "to": "2020-01",
    "months": 1,
    "industry": "Banking",
    "level": "Professional",
    "type": "Data Science Project",
    "naming": "keep anonymous",
    "organization": "McKinsey",
    "customer": "",
    "category": "Top 3 Banking Group",
    "country": "Germany",
    "role": "Project lead",
    "resp": "Strategy, Communication, Stakeholder Mgmt",
    "tech": "Powerpoint, Pen & Paper",
    "ref": "yes",
    "desc_en": "Developed a Data Science strategy – vision, roadmap, use-case evaluation, Data Science team setup within the organization – including executive workshops in the German insurance and banking sectors.",
    "desc_de": "Entwicklung einer Data-Science-Strategie – Vision, Roadmap, Use-Case-Evaluation, Data-Science-Team-Aufbau in der Organisation usw. – inklusive Executive-Workshops im deutschen Versicherungs- und Bankensektor."
  },
  {
    "num": 24,
    "from": "2020-01",
    "to": "2020-10",
    "months": 10,
    "industry": "Pharma",
    "level": "Professional",
    "type": "Data Science Project",
    "naming": "keep anonymous",
    "organization": "McKinsey",
    "customer": "",
    "category": "Top 3 Pharmaceutical Company",
    "country": "Germany",
    "role": "Project lead",
    "resp": "Implementation, Communication, Stakeholder Mgmt",
    "tech": "Python, Kedro, Tableau, Powerpoint",
    "ref": "yes",
    "desc_en": "Geo-intelligence: Built a portfolio of Analytics use cases for a top 5 drug in Germany (by revenue) at a large pharma company, leveraging internal and external (IQVIA) datasets, focusing on predicting drug prescriptions across German area codes and optimizing salesforce actions to improve commercial outcomes. Applied pharma-specific modelling methodologies ('brick-breaking').",
    "desc_de": "Geo-Intelligence: Aufbau eines Portfolios von Analytics-Use-Cases für ein Top-5-Medikament in Deutschland (nach Umsatz) bei einem großen Pharmaunternehmen, unter Nutzung interner und externer (IQVIA) Datenquellen, mit Fokus auf der Vorhersage von Verschreibungen über deutsche Postleitzahlbereiche sowie Optimierung des Außendienst-Vorgehens zur Verbesserung der gewünschten Outcomes. Einsatz pharmaspezifischer Modellierungs-Methoden ('Brick-Breaking')."
  },
  {
    "num": 25,
    "from": "2020-10",
    "to": "2020-10",
    "months": 0.5,
    "industry": "Pharma",
    "level": "Professional",
    "type": "Project Proposal",
    "naming": "keep anonymous",
    "organization": "McKinsey",
    "customer": "",
    "category": "Top 10 Pharmaceutical Company",
    "country": "Germany",
    "role": "Project member",
    "resp": "Communication",
    "tech": "Powerpoint",
    "ref": "",
    "desc_en": "Wrote project proposals for new Data Science engagements.",
    "desc_de": "Verfassen von Projektvorschlägen für neue Data-Science-Engagements."
  },
  {
    "num": 26,
    "from": "2020-10",
    "to": "2020-11",
    "months": 0.5,
    "industry": "Retail",
    "level": "Professional",
    "type": "Project Proposal",
    "naming": "keep anonymous",
    "organization": "McKinsey",
    "customer": "",
    "category": "Top 3 Retailer",
    "country": "Germany",
    "role": "Project member",
    "resp": "Communication",
    "tech": "Powerpoint",
    "ref": "",
    "desc_en": "Wrote project proposals for new Data Science engagements.",
    "desc_de": "Verfassen von Projektvorschlägen für neue Data-Science-Engagements."
  },
  {
    "num": 27,
    "from": "2020-11",
    "to": "2021-01",
    "months": 3,
    "industry": "Energy",
    "level": "Professional",
    "type": "Data Science Project",
    "naming": "keep anonymous",
    "organization": "McKinsey",
    "customer": "",
    "category": "Top 3 Energy Company",
    "country": "Germany",
    "role": "Project lead",
    "resp": "Implementation, Communication, Stakeholder Mgmt",
    "tech": "Python, Tableau, Excel, Powerpoint",
    "ref": "yes",
    "desc_en": "360-degree network visibility: Led a team building 30 Tableau dashboards to better understand the end-to-end activities of a large German utilities company, including voltage, parts (including faulty ones) and maintenance schedules to optimize overall operations.",
    "desc_de": "360-Grad-Netzwerk-Sichtbarkeit: Leitung eines Teams beim Aufbau von 30 Tableau-Dashboards zum besseren Verständnis der End-to-End-Aktivitäten eines großen deutschen Energieversorgers — inklusive Spannung, (fehlerhaften) Bauteilen und Wartungsplänen zur Optimierung des Gesamtbetriebs."
  },
  {
    "num": 28,
    "from": "2021-01",
    "to": "2021-12",
    "months": 11,
    "industry": "Pharma",
    "level": "Professional",
    "type": "Data Science Project",
    "naming": "keep anonymous",
    "organization": "McKinsey",
    "customer": "",
    "category": "Top 3 Pharma Wholesaler",
    "country": "Germany",
    "role": "Project lead",
    "resp": "Strategy, Communication, Stakeholder Mgmt",
    "tech": "SQL, Excel, Powerpoint",
    "ref": "yes",
    "desc_en": "Controlling & profit intelligence: Led the conceptualization and implementation of a complex cost breakdown to obtain EBITDA-profit numbers at transaction-level for Europe's largest pharma wholesaler. Applied to 750+ billion lines of item-level transactions. Led the team building a set of dashboards for informing more granular business decisions; this tool became a personal favorite of the organization's Chairman of the Board.",
    "desc_de": "Controlling & Profit Intelligence: Leitung der Konzeption und Umsetzung eines komplexen Cost-Breakdowns zur Ermittlung von EBITDA-Profit-Zahlen auf Transaktionsebene für den größten Pharma-Großhändler Europas. Angewendet auf 750+ Milliarden Item-Level-Transaktionszeilen. Leitung eines Teams beim Aufbau eines Sets von Dashboards für granulare Geschäftsentscheidungen; das Tool wurde zum persönlichen Favoriten des Vorstandsvorsitzenden der Organisation."
  },
  {
    "num": 29,
    "from": "2022-01",
    "to": "2022-10",
    "months": 10,
    "industry": "Information Technology",
    "level": "Professional",
    "type": "Sales & Pre-Sales",
    "naming": "ok to name",
    "organization": "DataRobot",
    "customer": "",
    "category": "30+ German Enterprise (DAX, Mittelstand)",
    "category_short": "30+ Enterprises",
    "country": "Germany",
    "role": "Account Executive & Forward-Deployed Engineer",
    "role_short": "AE & FDE",
    "resp": "Sales, Implementation, Communication, Stakeholder Mgmt",
    "tech": "DataRobot AI Platform, Python",
    "ref": "yes",
    "desc_en": "DataRobot enterprise sales & forward-deployed engineering across DACH: combined two complementary roles into one 11-month footprint — Sales Meetings with 30+ enterprise prospects (DAX and large mid-market) and hands-on Proof-of-Value projects with their data science teams in 2–4-week sprints, building rapid prototypes on DataRobot's AI cloud platform to demonstrate measurable impact. Promoted from PreSales to Sales Rep after 3 months. Led technical sales on build vs. buy decisions, platform due diligence, and consumption- vs seat-based commercial models. Delivered dedicated data/analytics enablement sessions for non-technical customer stakeholders.",
    "desc_de": "DataRobot Enterprise-Sales & Forward-Deployed Engineering in DACH: zwei sich ergänzende Rollen in einem 11-Monats-Engagement — Sales-Meetings mit 30+ Enterprise-Prospects (DAX und großer Mittelstand) und Hands-on-Proof-of-Value-Projekte mit deren Data-Science-Teams in 2–4-Wochen-Sprints, Aufbau schneller Prototypen auf DataRobots AI-Cloud-Plattform zur Demonstration messbaren Impacts. Nach 3 Monaten von PreSales in Sales-Rep befördert. Technische Sales-Gespräche zu Build vs. Buy, Plattform-Due-Diligence und Consumption- vs. Seat-basierten Commercial Models. Durchführung dedizierter Data-/Analytics-Enablement-Sessions für nicht-technische Stakeholder beim Kunden."
  },
  {
    "num": 30,
    "from": "2022-10",
    "to": "2023-01",
    "months": 4,
    "industry": "Information Technology",
    "level": "Professional",
    "type": "Data Science Project",
    "naming": "keep anonymous",
    "organization": "Waterland Private Equity",
    "customer": "",
    "category": "Top 15 IT-Dienstleistungsunternehmen",
    "country": "Germany",
    "role": "Project lead",
    "resp": "Implementation, Communication, Stakeholder Mgmt",
    "tech": "Python, Excel",
    "ref": "yes",
    "desc_en": "Embedded with a Waterland Private Equity portfolio company (top 15 German IT services provider). Created data transparency by improving the DWH and shipped executive dashboards used by the leadership team.",
    "desc_de": "Eingebettet bei einem Portfoliounternehmen von Waterland Private Equity (Top-15-IT-Dienstleister in Deutschland). Schaffung von Datentransparenz durch DWH-Verbesserung und Auslieferung von Executive-Dashboards für das Leadership-Team."
  },
  {
    "num": 31,
    "from": "2022-11",
    "to": "2023-02",
    "months": 4,
    "industry": "Manufacturing",
    "level": "Professional",
    "type": "Data Science Project",
    "naming": "ok to name",
    "organization": "Sennheiser",
    "customer": "Sennheiser",
    "category": "",
    "country": "Germany",
    "role": "Project lead",
    "resp": "Communication, Stakeholder Mgmt",
    "tech": "Powerpoint, Pen & Paper",
    "ref": "yes",
    "desc_en": "Data Science / AI strategy work at Sennheiser — executive workshops to identify and prioritize Data Science use cases across the organization, including vision and roadmap.",
    "desc_de": "Data-Science- / AI-Strategie-Arbeit bei Sennheiser — Executive-Workshops zur Identifikation und Priorisierung von Data-Science-Use-Cases im Unternehmen, inklusive Vision und Roadmap."
  },
  {
    "num": 32,
    "from": "2023-03",
    "to": "2025-03",
    "months": 24,
    "industry": "Insurance",
    "level": "Professional",
    "type": "Data Science Project",
    "naming": "keep anonymous",
    "organization": "QuantCo",
    "customer": "",
    "category": "Top 5 Insurance",
    "country": "Germany",
    "role": "Project lead",
    "resp": "Communication, Stakeholder Mgmt",
    "tech": "OpenAI GPT-4, Python, Postgres, Domino Data Lab",
    "ref": "yes",
    "desc_en": "AI & GenAI Efficiency Program at a top 5 German insurer: Project lead in T-role — oversight across all efficiency initiatives spanning the digital-native and traditional insurance arms, plus tech lead on two of them. Responded to a mid-engagement leadership change and top-down strategy pivot (digital native as innovator, traditional as fast follower) by redesigning the use-case priority stack and project plan from scratch without moving the original timeline — accounting for staffing constraints and tech dependencies, re-aligning stakeholders on both sides, and restarting execution within two weeks. Built central PMO and value-measurement function. Led Task Force on bill-dispatch optimization, preventing ~20,000 customer cancellations and delivering €2.5M profit impact. Project lead on the 'efficiency subproject', managing 7+ use cases including an email-prioritization solution.",
    "desc_de": "AI- & GenAI-Effizienz-Programm bei einem Top-5-Versicherer in Deutschland: Projektleitung in T-Rolle — Oversight über alle Effizienz-Initiativen in den Digital-Native- und Traditional-Insurance-Armen, plus Tech-Lead für zwei davon. Reaktion auf mid-engagement Leadership-Wechsel und Top-Down-Strategiewende (Digital-Native als Innovator, Traditional als Fast-Follower) durch Neugestaltung des Use-Case-Prioritäten-Stacks und Projektplans von Grund auf — bei gleichbleibender ursprünglicher Timeline — unter Berücksichtigung von Staffing-Restriktionen und Tech-Abhängigkeiten, Re-Alignment der Stakeholder beider Seiten und Wiederaufnahme der Umsetzung innerhalb von zwei Wochen. Aufbau einer zentralen PMO- und Mehrwert-Mess-Funktion. Leitung der Task Force für Rechnungsversand-Optimierung — Verhinderung von ~20.000 Kundenkündigungen und Lieferung von 2,5 Mio. € Profit-Impact. Projektleitung des 'Effizienz-Teilprojekts', mit Management von 7+ Use Cases inklusive einer E-Mail-Priorisierungs-Lösung."
  },
  {
    "num": 33,
    "from": "2025-03",
    "to": "2026-03",
    "months": 12,
    "industry": "Insurance",
    "level": "Professional",
    "type": "Data Science Project",
    "naming": "keep anonymous",
    "organization": "QuantCo",
    "customer": "",
    "category": "Top 3 Insurance",
    "country": "Switzerland",
    "role": "Project lead",
    "resp": "Communication, Stakeholder Mgmt",
    "tech": "Claude, OpenAI GPT-4, Gemini, LangChain, LangSmith, Python",
    "ref": "yes",
    "desc_en": "GenAI@Underwriting at a top 3 Swiss insurer: Led the team that built and shipped the customer's first two production GenAI solutions in Underwriting — a Correspondence Assistant and a Knowledge Assistant — delivering ~CHF 1M p.a. in measurable impact. C-level exposure including direct presentation to the Head of Underwriting. Initiated and drove additional AI experiments in the underwriting unit in partnership with the business lead.",
    "desc_de": "GenAI@Underwriting bei einem Top-3-Schweizer Versicherer: Leitung des Teams, das die ersten zwei produktiven GenAI-Lösungen des Kunden im Underwriting gebaut und ausgerollt hat — einen Correspondence Assistant und einen Knowledge Assistant — mit ~CHF 1 Mio. p.a. messbarem Impact. C-Level-Exposure inklusive direkter Präsentation vor dem Head of Underwriting. Initiierung und Treiber zusätzlicher AI-Experimente in der Underwriting-Einheit in Zusammenarbeit mit dem Business Lead."
  },
  {
    "num": 34,
    "from": "2026-03",
    "to": "2026-05",
    "months": 3,
    "industry": "Insurance",
    "level": "Professional",
    "type": "Data Science Project",
    "naming": "keep anonymous",
    "organization": "QuantCo",
    "customer": "",
    "category": "Top 5 Insurance",
    "country": "Germany",
    "role": "Project lead",
    "resp": "Communication, Stakeholder Mgmt",
    "tech": "Python, Domino Data Lab",
    "ref": "yes",
    "desc_en": "Application-process risk underwriting at a top 5 German insurer: Project lead with a team of three. Integrating credit-bureau scores and additional risk signals (low creditworthiness, pending dunning or insolvency proceedings) into the contract-application flow, with financial-impact modeling and corresponding process adjustments for flagged applicants.",
    "desc_de": "Risiko-Underwriting im Antragsprozess bei einem Top-5-Versicherer in Deutschland: Projektleitung mit einem Team von drei. Integration von Auskunfteien-Scores (SCHUFA, Experian, CRIF) und weiteren Risiko-Signalen — geringe Bonität, anhängige Mahn- oder Insolvenzverfahren — in den Vertragsantragsprozess, mit Financial-Impact-Modellierung und entsprechenden Prozessanpassungen für markierte Antragsteller:innen.",
    "to_projected": "2026-12"
  }
];
